api_platform:
    title: School Matching API
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Domain']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
